### ISSUE TITLE
Cloud-init network configuration fails in Debian/buster/cloud/amd64 image 

### ISSUE THREAD

**Issue by mjrider** [lxc/lxc-ci#166]
Enviroment:
network: without dhcp, all interfaces need a static allocation

partial config with both methods of defining the dns resolvers
```
architecture: x86_64
config:
  boot.autostart: "1"
  image.architecture: amd64
  image.description: Debian buster amd64 (20200609_05:24)
  image.os: Debian
  image.release: buster
  image.serial: "20200609_05:24"
  user.network-config: "version: 1\nconfig:\n  - type: physical\n    name: eth0\n
    \   subnets:\n      - type: static\n        address: 10.53.2.170\n        netmask:
    255.255.255.0\n        gateway: 10.53.2.1\n        control: auto\n  - type: nameserver\n
    \   address: \n      - 10.53.1.101\n      - 10.53.1.102\n"
  user.user-data: |
    #cloud-config
    manage_etc_hosts: true
    manage_resolv_conf: true

    resolv_conf:
      nameservers:
        - 10.53.1.101
        - 10.53.1.102
      options:
        rotate: true
        timeout: 1
  volatile.base_image: 54d80ea17c872cc0964c55a219c1625375f313d25619aabd9e05936a5b1a2120

```

This results in:
- empty /etc/resolv.conf file, because the package resolvconf ( or alternative ) is missing
- slow boot, because of hardcoded eth0 dhcp in /etc/network/interfaces (https://github.com/lxc/lxc-ci/blob/master/images/debian.yaml#L856)
