### ISSUE TITLE
images:centos/8 doesn't contain NetworkManager nor network-scripts

### ISSUE THREAD

**Issue by visit1985** [lxc/lxc-ci#348]
The current `images:centos/8` doesn't contain NetworkManager nor network-scripts.

It has `/etc/sysconfig/network-scripts/ifcfg-eth0`, but no process picking it up.

`dnf list installed | grep -i network` shows nothing.

<details>
  <summary>lxc image list --format yaml</summary>
  
  ```
  - auto_update: true
    properties:
      architecture: amd64
      description: Centos 8 amd64 (20210711_07:08)
      os: Centos
      release: "8"
      serial: "20210711_07:08"
      type: squashfs
      variant: default
    public: false
    expires_at: 1970-01-01T00:00:00Z
    profiles:
    - default
    aliases: []
    architecture: x86_64
    cached: false
    filename: lxd.tar.xz
    fingerprint: ca5d063ca282b05e3c288e8d299452c12e015618bfadda734c1b0fcc52dd2fe7
    size: 130007896
    update_source:
      alias: centos/8
      certificate: ""
      protocol: simplestreams
      server: https://images.linuxcontainers.org
      image_type: ""
    type: container
    created_at: 2021-07-11T00:00:00Z
    last_used_at: 2021-07-12T08:21:56.489479795Z
    uploaded_at: 2021-07-11T10:00:43.23921111Z
  ```
</details>
