### ISSUE TITLE
NixOS images

### ISSUE THREAD

**Issue by adamcstephens** [lxc/lxc-ci#786]
Hello. I've recently improved the NixOS support for building LXC container images and LXD virtual machine images. I originally investigated using distrobuilder to do so, but it was mostly trying to fit a square peg into a round hole. Nix already provides all the necessary build infrastructure that works with NixOS, and distrobuilder makes way too many assumptions about building a typical Linux distro that do not apply to Nix. 

My question here is, would it be possible to consume the images that the Nix CI builds so that they can be served through the linuxcontainers image server? Effectively the builder would only need to retrieve the latest tarballs/images that are already being produced.

It looks like NixOS supported was requested way back in #38 and the guidance was to use distrobuilder, but I'm hopeful we can find a compromise that does not meet that guidance. Thanks!

**Comment by stgraber** [comment]
It's not impossible but it's definitely not our preference.

What's the issue with distrobuilder exactly?
There already are quite a few images which are pretty thin repack performed by distrobuilder where a mostly complete rootfs is downloaded from an existing source, gets validated and then only some config files get put in place or in more extreme cases, just the image metadata files.

**Comment by adamcstephens** [comment]
NixOS expects and enforces that configuration is produced by the defined system configuration. For example all of `/etc/systemd` is symlinks to read-only files in the Nix store, `/nix/store/....`. So even the act of generating configuration should be done through NixOS tooling and not externally. None of the distrobuilder assumptions around package installation, network configuration, systemd overrides, etc, work with how NixOS expects the system to be configured. Distrobuilder also makes many assumptions about the existence of /usr, /sbin, /lib, that do not exist on a NixOS system.

I asked for some guidance a year ago [on discourse](https://discuss.linuxcontainers.org/t/nixos-image-building/14999) but ended up not getting any feedback. One thing I remember (and see in my posts from the time) is that the container images we produce through the NixOS CI aren't even chrootable [until this script snippet executes](https://github.com/NixOS/nixpkgs/blob/63ff76729b7359cd01e4ce09455b6af6c45f7286/nixos/modules/virtualisation/lxc-container.nix#L28-L36) on first boot.

These are just some of the challenges and are due to NixOS being fundamentally incompatible with assumptions that are safe on almost any other distro.

**Comment by adamcstephens** [comment]
Even if distrobuilder was extended to support building NixOS images, all of the relevant configuration will also need to live in the nixpkgs repository. NixOS configuration is delcarative. So for example, if a service were defined in the configuration built during image building, and it was not present when users went to modify the NixOS configuration, any changes would be removed as they would be no longer be in the new desired configuration.

**Comment by stgraber** [comment]
Do you have a functional NixOS image that will work through `lxc image import`?

**Comment by stgraber** [comment]
@adamcstephens can you test:
 - https://dl.stgraber.org/nixos/incus.tar.xz
 - https://dl.stgraber.org/nixos/rootfs.squashfs

And see if that works for you?

If it does, then I have a basic distrobuilder source and YAML that will pull your image and generate an equivalent metadata to yours.

**Comment by stgraber** [comment]
distrobuilder:
```patch
diff --git a/shared/definition.go b/shared/definition.go
index 84eb3dc..c8294f5 100644
--- a/shared/definition.go
+++ b/shared/definition.go
@@ -382,6 +382,7 @@ func (d *Definition) Validate() error {
                "rockylinux-http",
                "vyos-http",
                "slackware-http",
+               "nixos-http",
        }
 
        if !shared.StringInSlice(strings.TrimSpace(d.Source.Downloader), validDownloaders) {
diff --git a/sources/nixos-http.go b/sources/nixos-http.go
new file mode 100644
index 0000000..0ad3fbb
--- /dev/null
+++ b/sources/nixos-http.go
@@ -0,0 +1,28 @@
+package sources
+
+import (
+       "fmt"
+       "path/filepath"
+
+       "github.com/lxc/distrobuilder/shared"
+)
+
+type nixos struct {
+       common
+}
+
+func (s *nixos) Run() error {
+       tarballURL := fmt.Sprintf("https://hydra.nixos.org/job/nixos/trunk-combined/nixos.lxdContainerImage.%s-linux/latest/download-by-type/file/system-tarball", s.definition.Image.ArchitectureMapped)
+
+       fpath, err := s.DownloadHash(s.definition.Image, tarballURL, "", nil)
+       if err != nil {
+               return fmt.Errorf("Failed downloading tarball: %w", err)
+       }
+
+       err = shared.Unpack(filepath.Join(fpath, "system-tarball"), s.rootfsDir)
+       if err != nil {
+               return fmt.Errorf("Failed unpacking rootfs: %w", err)
+       }
+
+       return nil
+}
diff --git a/sources/source.go b/sources/source.go
index 9e2e3b9..906ec7a 100644
--- a/sources/source.go
+++ b/sources/source.go
@@ -36,6 +36,7 @@ var downloaders = map[string]func() downloader{
        "fedora-http":          func() downloader { return &fedora{} },
        "funtoo-http":          func() downloader { return &funtoo{} },
        "gentoo-http":          func() downloader { return &gentoo{} },
+       "nixos-http":           func() downloader { return &nixos{} },
        "openeuler-http":       func() downloader { return &openEuler{} },
        "opensuse-http":        func() downloader { return &opensuse{} },
        "openwrt-http":         func() downloader { return &openwrt{} },
```

YAML:
```yaml
image:
  distribution: nixos
  release: Tapir

source:
  downloader: nixos-http

targets:
  lxc:
    create_message: |
      You just created an {{ image.description }} container.

    config:
    - type: all
      after: 4
      content: |-
        lxc.include = LXC_TEMPLATE_CONFIG/common.conf

    - type: user
      after: 4
      content: |-
        lxc.include = LXC_TEMPLATE_CONFIG/userns.conf

    - type: all
      content: |-
        lxc.arch = {{ image.architecture_kernel }}

packages:
  custom_manager:
    clean:
      cmd: true
    install:
      cmd: true
    remove:
      cmd: true
    refresh:
      cmd: true
    update:
      cmd: true

files:
  - name: conf-hostname
    path: /etc/nixos/lxd.nix
    generator: template
    content: |-
      { lib, config, pkgs, ... }:

      # WARNING: THIS CONFIGURATION IS AUTOGENERATED AND WILL BE OVERWRITTEN AUTOMATICALLY

      {
        networking.hostName = "{{ instance.name }}";
      }
```
