### ISSUE TITLE
debian bookworm systemd networking is lacking - setting up multiple routes on 2 interfaces with cloud-init

### ISSUE THREAD

**Issue by invizus** [lxc/lxc-ci#820]
Using debian/bookworm/cloud container image

Hello. I was wondering whether decision to go with systemd networking was made by LXC project? I think official debian cloud instance (qcow2 for KVM in my case) comes with netplan.

My question: is cloud-init and systemd networking not entirely compatible, or is my cloud-init config incorrect?
This might sound like a question for cloud-init rather than lxc maintainers. And I would not expect LXC to move from systemd to other network manager for bookworm releases?

My goal:
My infrastructure has few various types of containers, different packages and configs, But most of them are apache2 instances. My goal was either create templates and reset cloud-init in them, which at the moment I see as manual process, but will think how to script it, OR create terraform code for various types of instances and just start from terraform + ansible to configure.

At the moment I am trying to start instances `incus create ... < cloud-init.yml` with cloud-init only. No terraform.

## first approach
Here is my scenario, part of my cloud-init setup:
```
config:
  cloud-init.network-config: |
    version: 1
    config: 
      - type: physical
        name: eth0 
        subnets:
          - type: static
            ipv4: true
            address: 192.168.2.15
            netmask: 255.255.255.0
            gateway: 192.168.2.1
            control: auto
      - type: physical
        name: eth1
        subnets:
          - type: static
            ipv4: true
            address: 192.168.3.15
            netmask: 255.255.255.0
            control: auto
      - type: nameserver
        address: 1.1.1.1
      - type: route
        destination: 10.10.125.0/24
        gateway: 192.168.3.20
      - type: route
        destination: 10.10.24.0/24
        gateway: 192.168.3.20
      - type: route
        destination: 192.168.19.0/24
        gateway: 192.168.3.20
```
resulting routes:
```
root@test-170:~# ip route
10.10.24.0/24 via 192.168.3.20 dev eth1 proto static 
10.10.24.0/24 via 192.168.2.1 dev eth0 proto static 
192.168.3.0/24 dev eth1 proto kernel scope link src 192.168.3.15 
192.168.2.0/24 dev eth0 proto kernel scope link src 192.168.2.15
```
contents of /etc/systemd/network/
```
root@test-170:/etc/systemd/network# grep -nr .
10-cloud-init-eth0.network:1:[Address]
10-cloud-init-eth0.network:2:Address=192.168.2.15/24
10-cloud-init-eth0.network:4:[Match]
10-cloud-init-eth0.network:5:Name=eth0
10-cloud-init-eth0.network:7:[Network]
10-cloud-init-eth0.network:8:DHCP=no
10-cloud-init-eth0.network:9:DNS=1.1.1.1
10-cloud-init-eth0.network:11:[Route]
10-cloud-init-eth0.network:12:Destination=10.10.125.0/24
10-cloud-init-eth0.network:13:Destination=10.10.19.0/24
10-cloud-init-eth0.network:14:Destination=10.10.24.0/24
10-cloud-init-eth0.network:15:Gateway=192.168.3.20
10-cloud-init-eth0.network:16:Gateway=192.168.2.1
10-cloud-init-eth1.network:1:[Address]
10-cloud-init-eth1.network:2:Address=192.168.3.15/24
10-cloud-init-eth1.network:4:[Match]
10-cloud-init-eth1.network:5:Name=eth1
10-cloud-init-eth1.network:7:[Network]
10-cloud-init-eth1.network:8:DHCP=no
10-cloud-init-eth1.network:9:DNS=1.1.1.1
10-cloud-init-eth1.network:11:[Route]
10-cloud-init-eth1.network:12:Destination=10.10.125.0/24
10-cloud-init-eth1.network:13:Destination=10.10.19.0/24
10-cloud-init-eth1.network:14:Destination=10.10.24.0/24
10-cloud-init-eth1.network:15:Gateway=192.168.3.20
eth0.network:1:[Match]
eth0.network:2:Name=eth0
eth0.network:4:[Network]
eth0.network:5:DHCP=true
eth0.network:7:[DHCPv4]
eth0.network:8:UseDomains=true
eth0.network:10:[DHCP]
eth0.network:11:ClientIdentifier=mac
```

## another approach
config
```
  cloud-init.network-config: |
    version: 1
    config:
      - type: physical
        name: eth0
        subnets:
          - type: static
            ipv4: true
            address: 192.168.2.15
            netmask: 255.255.255.0
            gateway: 192.168.2.1
            control: auto
      - type: nameserver
        address: 1.1.1.1
      - type: physical
        name: eth1
        subnets:
          - type: static
            ipv4: true
            address: 192.168.3.15
            netmask: 255.255.255.0
            control: auto
            routes:
              - gateway: 192.168.3.20
                netmask: 255.255.255.0
                network: 10.10.125.0
              - gateway: 192.168.3.20
                netmask: 255.255.255.0
                network: 10.10.24.0
              - gateway: 192.168.3.20
                netmask: 255.255.255.0
                network: 10.10.19.0

```

result
```
root@test-170:~# ip route
default via 192.168.2.1 dev eth0 proto static 
10.10.24.0/24 via 192.168.3.20 dev eth1 proto static 
192.168.3.0/24 dev eth1 proto kernel scope link src 192.168.3.15 
192.168.2.0/24 dev eth0 proto kernel scope link src 192.168.2.15
```
```
root@test-170:/etc/systemd/network# grep -nr .
10-cloud-init-eth0.network:1:[Address]
10-cloud-init-eth0.network:2:Address=192.168.2.15/24
10-cloud-init-eth0.network:4:[Match]
10-cloud-init-eth0.network:5:Name=eth0
10-cloud-init-eth0.network:7:[Network]
10-cloud-init-eth0.network:8:DHCP=no
10-cloud-init-eth0.network:9:DNS=1.1.1.1
10-cloud-init-eth0.network:11:[Route]
10-cloud-init-eth0.network:12:Gateway=192.168.2.1
10-cloud-init-eth1.network:1:[Address]
10-cloud-init-eth1.network:2:Address=192.168.3.15/24
10-cloud-init-eth1.network:4:[Match]
10-cloud-init-eth1.network:5:Name=eth1
10-cloud-init-eth1.network:7:[Network]
10-cloud-init-eth1.network:8:DHCP=no
10-cloud-init-eth1.network:9:DNS=1.1.1.1
10-cloud-init-eth1.network:11:[Route]
10-cloud-init-eth1.network:12:Destination=10.10.125.0/24
10-cloud-init-eth1.network:13:Destination=10.10.19.0/24
10-cloud-init-eth1.network:14:Destination=10.10.24.0/24
10-cloud-init-eth1.network:15:Gateway=192.168.3.20
eth0.network:1:[Match]
eth0.network:2:Name=eth0
eth0.network:4:[Network]
eth0.network:5:DHCP=true
eth0.network:7:[DHCPv4]
eth0.network:8:UseDomains=true
eth0.network:10:[DHCP]
eth0.network:11:ClientIdentifier=mac
```

## thoughts
I manually installed and configured netplan.io and used this as example config, works as I need. ( [example](https://people.ubuntu.com/~slyon/netplan-docs/examples/#using-dhcp-and-static-addressing). second block of code)

To configure routes in systemd, need to have one entry per destination/gateway, i.e.
```
[Route]
Destination=10.10.125.0/24
Gateway=192.168.3.20

[Route]
Destination=10.10.19.0/24
Gateway=192.168.3.20
```
