### ISSUE TITLE
ssh-import-id is missing in cloud variants

### ISSUE THREAD

**Issue by phish108** [lxc/lxc-ci#869]
While playing with cloud-init on `images:ubuntu/24.04/cloud`, I found the following message in the cloud-init output logs: 

```
cc_ssh_import_id.py[WARNING]: ssh-import-id is not installed, but module ssh_import_id is configured. Skipping module.
```

Adding this module would be very handy, so if openssh-server is installed through the `packages` directive, password less authentication would work from the get go. The `ssh-import-id` directive will be ignored, even if it is installed through the `packages` directive because cloud-init's user management tasks have completed at that point. 

Running the `ssh-import-id` step during the `runcmd` phase is more complex if multiple users are created on the instance. 

This might be specific to ubuntu, but is certainly also useful in other images of the cloud-variant. 

Thank you for considering.

**Comment by stgraber** [comment]
We don't install `openssh-server` by default in our images, so we can't install `ssh-import-id` without also pulling in `openssh-server`.

In theory you'd expect this to work:
```
  cloud-init.user-data: |-
    #cloud-config
    packages:
      - openssh-server
      - ssh-import-id
    users:
      - name: stgraber
        ssh_import_id:
          - gh:stgraber
```

But cloud-init appears to be running the check for `ssh-import-id` before the packages get installed, even if the account creation would most likely be processed after the package installation stage.

I'd argue this is a cloud-init bug and cloud-init should allow for `packages` to bring in `ssh-import-id` in this case.

@blackboxsw
